apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skd-poc
  namespace: okonomi
  labels:
    team: okonomi
spec:
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  ingresses:
    - https://sokos-skd-poc.dev.intern.nav.no



