apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ske-krav
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-ske-krav.intern.dev.nav.no
  secureLogs:
    enabled: true
  webproxy: true
  vault:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:innkrevingsoppdrag
  filesFrom:
    - secret: ske-sftp-private-key
      mountPath: /var/run/secrets/ske-sftp-private-key
    - secret: ske-sftp-host-key
      mountPath: /var/run/secrets/ske-sftp-host-key
  envFrom:
    - secret: ske-sftp-creds
  env:
    - name: SKE_REST_URL
      value: https://api-test.sits.no/api/innkreving/innkrevingsoppdrag/v1/
    - name: FTP_SERVER
      value: b27drvl011.preprod.local
    - name: FTP_PORT
      value: "22"
    - name: FTP_DIRECTORY
      value: "/"
    - name: POSTGRES_HOST
      value: b27dbvl030.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-skd-krav
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: SFTP_PRIVATE_KEY_FILE_PATH
      value: /var/run/secrets/ske-sftp-private-key/ske-sftp-private-key
    - name: SFTP_HOST_KEY_FILE_PATH
      value: /var/run/secrets/ske-sftp-host-key/ske-sftp-host-key