apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skd-poc
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  webproxy: true
  ingresses:
    - https://sokos-skd-poc.intern.dev.nav.no
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:innkrevingsoppdrag
  secureLogs:
    enabled: true
  vault:
    enabled: true
  env:
    - name: SKD_REST_URL
      value: https://api-test.sits.no/api/innkreving/innkrevingsoppdrag/v1/
    - name: FTP_SERVER
      value: "localhost"
    - name: FTP_USERNAME
      value: "ftpuser"
    - name: FTP_PASSWORD
      value: "123"
    - name: FTP_DIRECTORY
      value: "/"
    - name: FTP_PORT
      value: "0"




