apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ske-krav
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  webproxy: true
  envFrom:
    - secret: ske-sftp-creds
  ingresses:
    - https://sokos-ske-krav.intern.dev.nav.no
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:innkrevingsoppdrag
  secureLogs:
    enabled: true
  vault:
    enabled: true
  env:
    - name: SKE_REST_URL
      value: https://api-test.sits.no/api/innkreving/innkrevingsoppdrag/v1/
    - name: FTP_SERVER
      value: "b27drvl011.preprod.local"
    - name: FTP_PORT
      value: "22"
    - name: FTP_DIRECTORY
      value: "/"
    - name: POSTGRES_HOST
      value: b27dbvl030.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-skd-krav
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: LOG_APPENDER
      value: CONSOLE