package no.nav.sokos.ske.krav.domain

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Status(
    val value: String,
) {
    KRAV_INNLEST_FRA_FIL("KRAV_INNLEST_FRA_FIL"),
    KRAV_IKKE_SENDT("KRAV_IKKE_SENDT"),
    KRAV_SENDT("KRAV_SENDT"),
    MOTTATT_UNDER_BEHANDLING("MOTTATT_UNDER_BEHANDLING"),
    RESKONTROFOERT("RESKONTROFOERT"),
    MIGRERT("MIGRERT"),

    VALIDERINGSFEIL_AV_LINJE_I_FIL("VALIDERINGSFEIL_AV_LINJE_I_FIL"),

    @SerialName("VALIDERINGSFEIL")
    VALIDERINGSFEIL_MOTTAKSSTATUS("VALIDERINGSFEIL"),

    UKJENT_FEIL("UKJENT_FEIL"),
    UKJENT_STATUS("UKJENT_STATUS"),

    HTTP300_REDIRECTION_FEIL("300_SERIE_REDIRECTION_RESPONSE"),
    HTTP400_ANNEN_KLIENT_FEIL("400_SERIE_ANNEN_KLIENTFEIL"),
    HTTP400_UGYLDIG_FORESPORSEL("400_UGYLDIG_FORESPORSEL"),
    HTTP400_UGYLDIG_KRAVIDENTIFIKATOR("400_UGYLDIG_KRAVIDENTIFIKATOR"),
    HTTP400_UGYLDIG_TILLEGGSINFORMASJON("400_UGYLDIG_TILLEGGSINFORMASJON"),
    HTTP401_FEIL_AUTENTISERING("401_KLIENTEN_ER_IKKE_AUTENTISERT"),
    HTTP403_INGEN_TILGANG("403_KLIENTEN_ER_IKKE_AUTORISERT"),
    HTTP404_ANNEN_IKKE_FUNNET("404_ANNEN_IKKE_FUNNET"),
    HTTP404_FANT_IKKE_SAKSREF("404_SKE_FANT_IKKE_SAKSREF"),
    HTTP404_KRAV_ER_IKKE_RESKONTROFORT("404_KRAV_ER_IKKE_RESKONTROFØRT"),
    HTTP406_FEIL_MEDIETYPE("406_FEIL_MEDIETYPE_I_REQUEST"),
    HTTP409_ANNEN_KONFLIKT("409_ANNEN_KONFLIKT"),
    HTTP409_KRAV_ER_IKKE_RESKONTROFORT_RESEND("409_KRAV_ER_IKKE_RESKONTROFØRT_RESEND"),
    HTTP409_KRAV_ER_AVSKREVET("409_KRAV_ER_AVSKREVET"),
    HTTP409_AVSKREVET_KRAV_KAN_IKKE_ENDRES("409_AVSKREVET_KRAV_KAN_IKKE_ENDRES"),
    HTTP409_AVSKREVET_KRAV_KAN_IKKE_AVSKRIVES("409_AVSKREVET_KRAV_KAN_IKKE_AVSKRIVES"),
    HTTP409_KRAVIDENTIFIKATOR_EKSISTERER("409_KRAVIDENTIFIKATOR_EKSISTERER_ALLEREDE"),
    HTTP422_VALIDERINGSFEIL("422_VALIDERINGSFEIL"),
    HTTP500_ANNEN_SERVER_FEIL("500_SERIE_ANNEN_SERVER_FEIL"),
    HTTP500_INTERN_TJENERFEIL("500_FEIL_PÅ_MOTTAKSERVER"),
    HTTP503_UTILGJENGELIG_TJENESTE("503_TJENESTEN_ER_IKKE_TILGJENGELIG"),
}

fun String.toStatus() = runCatching { Status.valueOf(this) }.getOrElse { Status.entries.find { it.value == this } } ?: Status.UKJENT_STATUS
