package no.nav.sokos.ske.krav.domain

enum class StonadsType(
    val kravKode: String,
    val hjemmelkode: String,
    val alternativHjemmelkode: String = "",
) {
    TILBAKEKREVING_ALDERSPENSJON("PE AP", "T"),
    TILBAKEKREVING_ARBEIDSAVKLARINGSPENGER("AAP AAP", "T"),
    TILBAKEKREVING_AVTALEFESTET_PENSJON("PE XP", "T"),
    TILBAKEKREVING_AVTALEFESTET_PENSJON_PRIVATSEKTOR("PE AF", "T"),
    TILBAKEKREVING_BARNETRYGD("BA OR", "T"),
    TILBAKEKREVING_BARNEPENSJON("PE BP", "T"),
    TILBAKEKREVING_DAGPENGER("DP DP", "T"),
    TILBAKEKREVING_ENGANGSSTOENAD_VED_FOEDSEL("FA FE", "T"),
    TILBAKEKREVING_FORELDREPENGER("FA FØ", "T"),
    TILBAKEKREVING_FORSKUTTERTE_DAGPENGER("FO FT", "FT"),
    TILBAKEKREVING_GAMMEL_YRKESSKADEPENSJON("PE GY", "T"),
    TILBAKEKREVING_GJENLEVENDE_PENSJON("PE GP", "T"),
    TILBAKEKREVING_GJENLEVENDE_PENSJON_AVREGNING("PE GP", "TA"),
    TILBAKEKREVING_KOMPENSASJON_NAERING_OG_FRILANS("FR SN", "T"),
    TILBAKEKREVING_KONTANTSTOETTE("KS KS", "T"),
    TILBAKEKREVING_KRIGSPENSJON("PE KP", "T"),
    TILBAKEKREVING_LOENNSKOMPENSASJON("LK RF", "T"),
    TILBAKEKREVING_OMSORGSPENGER("BS OM", "T"),
    TILBAKEKREVING_OMSTILLINGSSTOENAD("OM OM", "T"),
    TILBAKEKREVING_OMSTILLINGSSTOENAD_ETTEROPPGJOER("OM OM", "EO"),
    TILBAKEKREVING_OPPLAERINGSPENGER("BS OP", "T"),
    TILBAKEKREVING_OVERGANGSSTOENAD("EF OG", "T"),
    TILBAKEKREVING_PERMITTERINGSPENGER_KORONA("LK LK", "T"),
    TILBAKEKREVING_PLEIEPENGER_BARN("BS PN", "T"),
    TILBAKEKREVING_PLEIEPENGER_NAERSTAAENDE("BS PP", "T"),
    TILBAKEKREVING_STOENAD_TIL_BARNETILSYN("EF BT", "T"),
    TILBAKEKREVING_SUPPLERENDE_STOENAD_ALDERSPENSJON("SU AP", "T"),
    TILBAKEKREVING_SUPPLERENDE_STOENAD_UFOEREPENSJON("SU UF", "T"),
    TILBAKEKREVING_SVANGERSKAPSPENGER("FA SV", "T"),
    TILBAKEKREVING_SYKEPENGER("KT SP", "T"),
    TILBAKEKREVING_TIDLIGERE_FAMILIEPLEIER_PENSJON("PE FP", "T"),
    TILBAKEKREVING_TILLEGGSTOENAD("TS TS", "T"),
    TILBAKEKREVING_TILTAKSPENGER("TP TP", "T"),
    TILBAKEKREVING_UFOEREPENSJON("PE UP", "T"),
    TILBAKEKREVING_UFOERETRYGD("PE UT", "T"),
    TILBAKEKREVING_UFOERETRYGD_AVREGNING("PE UT", "TA"),
    TILBAKEKREVING_UFOERETRYGD_ETTEROPPGJOER("PE UT", "EU"),
    TILBAKEKREVING_UNGDOMSPROGRAMYTELSEN("UNG", "T"),
    TILBAKEKREVING_UTDANNINGSSTOENAD("EF UT", "T"),

    ;

    companion object {
        fun getStonadstype(
            kravkode: String,
            kodeHjemmel: String,
        ): StonadsType =
            StonadsType.entries.firstOrNull {
                kravkode == it.kravKode && (kodeHjemmel == it.hjemmelkode || kodeHjemmel == it.alternativHjemmelkode)
            }
                ?: throw NotImplementedError(
                    "Kombinasjonen kravkode=$kravkode og hjemmelkode=$kodeHjemmel gir ingen kravtype.",
                )
    }
}
