package sokos.ske.krav.navmodels

enum class Stonadstype(val value: String){
    FORELDREPENGER("FA FØ"),
    KOMPENSASJONINNTEKSTAPFRILANSEROGNAERING("FR SN"),
    OMSORGOPPLAERINGOGPLEIEPENGER("KT OOP"),
    AVTALEFESTETPENSJON("PE XP"),
    AVTALEFESTETPENSJONPRIVATSEKTOR("PE AF"),
    ALDERSPENSJON("PE AP"),
    BARNEPENSJON("PE BP"),
    TIDLIGEREFAMILIEPLEIERPENSJON("PE FP"),
    GJENLEVENDEPENSJON("PE GP"),
    GAMMELYRKESSKADEPENSJON("PE GY"),
    KRIGSPENSJON("PE KP"),
    UFOEREPENSJON("PE UP"),
    REFUSSJONUTGIFTSDEKNING("FA FE"),
    SYKEPENGER("KT SP"),
    SVANGERSKAPSPENGER("FA SV"),
    UFOERETRYGD("PE UT"),
    FORSKUDDTILBAKEKREVING("FO FT"),
    PERMITERINGSPENGERKORONA("LK LK"),
    LOENSKOMPARBEIDSGIVERPERMITERTE("LK RF"),
    BARNETRYGD("BA OR"),
    OPPLAERINGSPENGER("BS OP"),
    OMSORGSPENGER("BS OM"),
    PLEIEPENGERBARN("BS PN"),
    PLEIEPENGERNAERSTAAENDE("BS PP"),
    ENSLIGFORSOERGEROVERGANGSSTOENAD("EF OG"),
    ENSLIGFORSOERGERBARNETILSYN("EF BT"),
    ENSLIGFORSOERGERSKOLEPENGER("EF UT"),
    SUPPLERENDESTOENADUFOERE("SU UF"),
    KONTANTSTOETTE("KS KS"),
    DAGPENGER("DAGPENGER");

    companion object {
        private val map = Stonadstype.values().associateBy { it.value }
        infix fun from(value: String) = map[value]
    }
}