include file("defaults.properties")

ktor {
  environment = local
}

application {
  appName = "sokos-ske-krav"
  appName = ${?NAIS_APP_NAME}
  useAuthentication = true
  basicUsername = ${?BASIC_AUTH_USERNAME}
  basicPassword = ${?BASIC_AUTH_PASSWORD}
}

azureAd {
  clientId = ${AZURE_APP_CLIENT_ID}
  wellKnownUrl = ${AZURE_APP_WELL_KNOWN_URL}
  tenantId = ${AZURE_APP_TENANT_ID}
  clientSecret = ${AZURE_APP_CLIENT_SECRET}
}

maskinportenClient {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
}

skeConfig {
  skeRestUrl = ${SKE_REST_URL}
}