include file("application.conf")

ktor {
  environment = prod
}

application {
  profile = PROD
}

sftp {
  host = "filmottak.adeo.no"
  privateKey = "/var/run/secrets/ske-sftp-private-key/ske-sftp-private-key"
}
