include file("application.conf")

ktor {
  environment = local
}

application {
  profile = LOCAL
  useAuthentication = false
}

sftp {
  host = "10.183.32.98"
  port = 22
  privateKeyFilePath = "privateKey"
}

ske {
  skeRestUrl = "https://innkrevingsoppdrag.innkreving.skatteetaten-test.no/api/innkreving/innkrevingsoppdrag/v1/"
}

postgres {
  host = "dev-pg.intern.nav.no"
  port = "5432"
  vaultMountPath = ""
}

circuitBreaker {
  waitDurationInOpenState = 2
}
