include file("defaults.properties")

ktor {
  environment = local
}

application {
  appName = "sokos-ske-krav"
  appName = ${?NAIS_APP_NAME}
  namespace = "okonomi"
  namespace = ${?NAIS_NAMESPACE}
  useAuthentication = true
  basicUsername = ${?BASIC_AUTH_USERNAME}
  basicPassword = ${?BASIC_AUTH_PASSWORD}
}

azureAd {
  clientId = ${AZURE_APP_CLIENT_ID}
  wellKnownUrl = ${AZURE_APP_WELL_KNOWN_URL}
  tenantId = ${AZURE_APP_TENANT_ID}
  clientSecret = ${AZURE_APP_CLIENT_SECRET}
}

sftp {
  username = ${SKE_SFTP_USERNAME}
  privateKeyPassword = ${SKE_SFTP_PASSWORD}
}

maskinportenClient {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
}

ske {
  skeRestUrl = ${SKE_REST_URL}
}

postgres {
  name = ${POSTGRES_NAME}
  username = ${POSTGRES_USERNAME}
  password = ${POSTGRES_PASSWORD}
}

slack {
  url = ${TEAM_BEST_SLACK_WEBHOOK_URL}
}

timer {
  useTimer = ${USE_TIMER}
  schedulerIntervalPeriodInt = ${TIMER_INTERVAL_PERIOD_HOURS}
}
