include file("application.conf")

ktor {
  environment = dev
}

application {
  profile = DEV
  useAuthentication = false
}

sftp {
  host = "b27drvl011.preprod.local"
  port = 22
  privateKeyFilePath = "/var/run/secrets/sokos-ske-krav-sftp-private-key/private-key"
}

ske {
  skeRestUrl = "https://innkrevingsoppdrag.innkreving.skatteetaten-test.no/api/innkreving/innkrevingsoppdrag/v1/"
}

postgres {
  host = "b27dbvl030.preprod.local"
  port = "5432"
  vaultMountPath = "postgresql/preprod-fss/"
}

circuitBreaker {
  waitDurationInOpenState = 2
}
