include file("defaults.properties")

ktor {
  environment = local
}

application {
  appName = "sokos-ske-krav"
  appName = ${?NAIS_APP_NAME}
  useAuthentication = true
  basicUsername = ${?BASIC_AUTH_USERNAME}
  basicPassword = ${?BASIC_AUTH_PASSWORD}
}