include file("application.conf")

ktor {
  environment = prod
}

application {
  profile = PROD
  useAuthentication = true
}


sftp {
  host = "filmottak.adeo.no"
  port = 22
  privateKeyFilePath = "/var/run/secrets/sokos-ske-krav-sftp-private-key/private-key"
}

ske {
  skeRestUrl = "https://innkrevingsoppdrag.innkreving.skatteetaten.no/api/innkreving/innkrevingsoppdrag/v1/"
}

postgres {
  host = "A01DBVL037.adeo.no"
  port = "5432"
  vaultMountPath = "postgresql/prod-fss/"
}

circuitBreaker {
  waitDurationInOpenState = 3
}
