include "application-local.conf"

ktor {
  environment = dev
}

application {
  profile = DEV
}

sftp {
  host = "b27drvl011.preprod.local"
  privateKeyFilePath = "/var/run/secrets/sokos-ske-krav-sftp-private-key/private-key"
}

postgres {
  host = "b27dbvl030.preprod.local"
  port = "5432"
  vaultMountPath = "postgresql/preprod-fss/"
}
