include file("application.conf")

ktor {
  environment = local
}

application {
  profile = LOCAL
  useAuthentication = false
  basicUsername = "user"
  basicPassword = "password"
}

sftp {
  host = "10.183.32.98"
  privateKeyFilePath = "privKey"
}

postgres {
  host = "dev-pg.intern.nav.no"
  vaultMountPath = ""
}

slack {
  url = ""
}

circuitBreaker {
  waitDurationInOpenState = 2
}

timer {
  useTimer = false
}
