application {
  appName = "sokos-ske-krav"
  appName = ${?NAIS_APP_NAME}
  basicPassword = ${?BASIC_AUTH_PASSWORD}
  basicUsername = ${?BASIC_AUTH_USERNAME}
  namespace = "okonomi"
  profile = PROD
  useAuthentication = true
}

azure {
  jwksUri = ${?AZURE_OPENID_CONFIG_JWKS_URI}
  configIssuer = ${?AZURE_OPENID_CONFIG_ISSUER}
  clientId = ${?AZURE_APP_CLIENT_ID}
}

circuitBreaker {
  waitDurationInOpenState = 3
}

ktor {
  environment = prod
}

maskinportenClient {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
}

postgres {
  host = ${?DB_HOST}
  name = ${?DB_DATABASE}
  password = ${?DB_PASSWORD}
  port = ${?DB_PORT}
  url = ${?DB_JDBC_URL}
  username = ${?DB_USERNAME}
}

sftp {
  host = "filmottak.adeo.no"
  port = 22
  privateKeyFilePath = "/var/run/secrets/sokos-ske-krav-sftp-private-key/private-key"
  privateKeyPassword = ${SKE_SFTP_PASSWORD}
  username = ${SKE_SFTP_USERNAME}
}

ske {
  skeRestUrl = "https://innkrevingsoppdrag.innkreving.skatteetaten.no/api/innkreving/innkrevingsoppdrag/v1/"
}

slack {
  slackIdDomainSpecialists = ${SOKOS_SKE_KRAV_SLACKID_DOMAINSPECIALISTS}
  slackIdProductLeader = ${SOKOS_SKE_KRAV_SLACKID_PRODUCTLEADER}
  slackIdTechnicalSpecialist = ${SOKOS_SKE_KRAV_SLACKID_TECHNICALSPECIALIST}
  url = ${SOKOS_SKE_KRAV_SLACK_WEBHOOK_URL}
}

timer {
  schedulerIntervalPeriodInt = 4
  useTimer = true
}
