ktor {
  environment = prod
}

application {
  profile = PROD
  appName = "sokos-ske-krav"
  appName = ${?NAIS_APP_NAME}
  namespace = "okonomi"
  useAuthentication = true
  basicUsername = ${?BASIC_AUTH_USERNAME}
  basicPassword = ${?BASIC_AUTH_PASSWORD}
}

sftp {
  host = "filmottak.adeo.no"
  port = 22
  username = ${SKE_SFTP_USERNAME}
  privateKeyPassword = ${SKE_SFTP_PASSWORD}
  privateKeyFilePath = "/var/run/secrets/sokos-ske-krav-sftp-private-key/private-key"
}

ske {
  skeRestUrl = "https://innkrevingsoppdrag.innkreving.skatteetaten.no/api/innkreving/innkrevingsoppdrag/v1/"
}

maskinportenClient {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
}

postgres {
  host = "A01DBVL037.adeo.no"
  port = "5432"
  name = "sokos-ske-krav"
  username = ${?POSTGRES_USERNAME}
  password = ${?POSTGRES_PASSWORD}
  vaultMountPath = "postgresql/prod-fss/"
}

slack {
  url = ${SOKOS_SKE_KRAV_SLACK_WEBHOOK_URL}
  slackIdProductLeader = ${SOKOS_SKE_KRAV_SLACKID_PRODUCTLEADER}
  slackIdDomainSpecialists = ${SOKOS_SKE_KRAV_SLACKID_DOMAINSPECIALISTS}
  slackIdTechnicalSpecialist = ${SOKOS_SKE_KRAV_SLACKID_TECHNICALSPECIALIST}
}

circuitBreaker {
  waitDurationInOpenState = 3
}

timer {
  useTimer = true
  schedulerIntervalPeriodInt = 4
}
