apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ske-krav
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  webproxy: true
  prometheus:
    enabled: true
    path: /internal/metrics
  filesFrom:
    - secret: sokos-ske-krav-sftp-private-key
      mountPath: /var/run/secrets/sokos-ske-krav-sftp-private-key
  envFrom:
    - secret: sokos-ske-krav-secrets
  ingresses:
    - https://sokos-ske-krav.intern.nav.no
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:innkrevingsoppdrag
  vault:
    enabled: true

  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:MaxRAMPercentage=75 --enable-native-access=ALL-UNNAMED $(JAVA_PROXY_OPTIONS)
