/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels

/**
 * 
 * @param kravidentifikatortype Hvilken type kravidentifikator som blir brukt i denne forespørselen.
 * @param kravidentifikator              Kravidentifikatoren til innkrevingsoppdraget som skal endres. Benyttes til å slå opp eksisterende              innkrevingsoppdrag og spore endringen. Kravidentifikatoren må tilhøre et innkrevingsoppdrag som er              reskontroført hos Skatteetaten.         
 * @param nyHovedstol 
 */
data class EndringRequest (

    /* Hvilken type kravidentifikator som blir brukt i denne forespørselen. */
    val kravidentifikatortype: Kravidentifikatortype,
    /*              Kravidentifikatoren til innkrevingsoppdraget som skal endres. Benyttes til å slå opp eksisterende              innkrevingsoppdrag og spore endringen. Kravidentifikatoren må tilhøre et innkrevingsoppdrag som er              reskontroført hos Skatteetaten.          */
    val kravidentifikator: kotlin.String,
    val nyHovedstol: HovedstolBeloep
) {
    /**
    * Hvilken type kravidentifikator som blir brukt i denne forespørselen.
    * Values: SKATTEETATENSKRAVIDENTIFIKATOR
    */
    enum class Kravidentifikatortype(val value: kotlin.String){
        SKATTEETATENSKRAVIDENTIFIKATOR("SKATTEETATENS_KRAVIDENTIFIKATOR");
    }
}