/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels

import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable

@Serializable
data class OpprettInnkrevingsoppdragRequest(

    val kravtype: String,
    val skyldner: Skyldner,
    val hovedstol: HovedstolBeloep,
    val renteBeloep: Array<RenteBeloep>?,
    val oppdragsgiversSaksnummer: String,
    val oppdragsgiversKravidentifikator: String,
    val fastsettelsesdato: LocalDate,
    val foreldelsesfristensUtgangspunkt: LocalDate? = null,
    val tilleggsinformasjon: TilleggsinformasjonNav? = null
) {
    enum class Kravtype(val value: String){
        TILBAKEKREVINGFEILUTBETALTYTELSE("TILBAKEKREVING_FEILUTBETALT_YTELSE"),
        FORSIKRINGSPREMIESELVSTENDIGNAERINGSDRIVENDE("FORSIKRINGSPREMIE_SELVSTENDIG_NAERINGSDRIVENDE");
    }
}