/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels


/**
 * Simpelt resultatobjekt for vellykket opprettelse av nytt innkrevingsoppdrag
 * @param kravidentifikator              Kravidentifikator innkrevingsoppdraget fikk hos Skatteetaten         
 */
data class OpprettInnkrevingsoppdragResponse (

    /*              Kravidentifikator innkrevingsoppdraget fikk hos Skatteetaten          */
    val kravidentifikator: kotlin.String
) {
}