/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * Tjeneste for å opprette innkrevingsoppdrag
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels


/**
 *              Hvem som skylder penger.         
 * @param identifikatortype              Per nå støttes kun PERSON og ORGANISASJON som aktuelle typer parter innkrevingsmyndighet             kan kreve inn fra.         
 * @param identifikator              Må være et gyldig fnr/dnr, eller orgnr.         
 */
data class Skyldner (

    /*              Per nå støttes kun PERSON og ORGANISASJON som aktuelle typer parter innkrevingsmyndighet             kan kreve inn fra.          */
    val identifikatortype: Identifikatortype,
    /*              Må være et gyldig fnr/dnr, eller orgnr.          */
    val identifikator: kotlin.String
) {
    /**
    *              Per nå støttes kun PERSON og ORGANISASJON som aktuelle typer parter innkrevingsmyndighet             kan kreve inn fra.         
    * Values: PERSON,ORGANISASJON
    */
    enum class Identifikatortype(val value: kotlin.String){
        PERSON("PERSON"),
        ORGANISASJON("ORGANISASJON");
    }
}