/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * Tjeneste for å opprette innkrevingsoppdrag
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels


/**
 * Tilleggsinformasjon spesifikt per oppdragsgiver, angis etter avtale med Skatteetaten.Se egne objekter for det som gjelder per oppdragsgiver
 */
class Tilleggsinformasjon (

) {
}