/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels


/**
 *              Liste over alle eventuelle valideringsfeil som oppstod ved forespørsel om nytt innkrevingsoppdrag.             Gir tom liste dersom ingen finnes for gitt kravidentifikator.         
 * @param error              Feilkode for valderingsfeilen         
 * @param message              Utfyllende beskrivelse av valideringsfeilen         
 */
data class ValideringsfeilDTO (

    /*              Feilkode for valderingsfeilen          */
    val error: kotlin.String,
    /*              Utfyllende beskrivelse av valideringsfeilen          */
    val message: kotlin.String
) {
}