/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package sokos.skd.poc.skdmodels

import kotlinx.serialization.Serializable


/**
 *              Total ytelse tilgjengelig for avregning, om noe. Benyttes av innkrevingsmyndigheten ved \"avregning\"             som innkrevingstiltak.         
 * @param valuta Kun norske kroner støttes per nå.
 * @param beloep Heltall, desimaler støttes ikke. Avrunding må i så fall gjøres hos oppdragsgiver. Angis som hovedenhet i valutaen, dvs. kroner ikke ører, euro ikke cent, osv. 
 */

@Serializable
data class YtelseForAvregningBeloep (

    /* Kun norske kroner støttes per nå. */
    val valuta: Valuta,
    /* Heltall, desimaler støttes ikke. Avrunding må i så fall gjøres hos oppdragsgiver. Angis som hovedenhet i valutaen, dvs. kroner ikke ører, euro ikke cent, osv.  */
    val beloep: Long
) {
    /**
    * Kun norske kroner støttes per nå.
    * Values: NOK
    */
    enum class Valuta(val value: String){
        NOK("NOK");
    }
}