package sokos.ske.krav.domain

enum class Status(val value: String) {
    KRAV_INNLEST_FRA_FIL("KRAV_INNLEST_FRA_FIL"),
    KRAV_IKKE_SENDT("KRAV_IKKE_SENDT"),
    KRAV_SENDT("KRAV_SENDT"),
    MOTTATT_UNDERBEHANDLING("MOTTATT_UNDER_BEHANDLING"),
    RESKONTROFOERT("RESKONTROFOERT"),

    VALIDERINGSFEIL_AV_LINJE_I_FIL("VALIDERINGSFEIL_AV_LINJE_I_FIL"),
    VALIDERINGSFEIL_MOTTAKSSTATUS("VALIDERINGSFEIL"),
    VALIDERINGFEIL_RAPPORTERT("VALIDERINGSFEIL_RAPPORTERT"),

    UKJENT_FEIL("UKJENT_FEIL"),
    UKJENT_STATUS("UKJENT_STATUS"),

    HTTP300_REDIRECTION_FEIL("300_SERIE_REDIRECTION_RESPONSE"),
    HTTP400_ANNEN_KLIENT_FEIL("400_SERIE_ANNEN_KLIENTFEIL"),
    HTTP400_UGYLDIG_FORESPORSEL("400_UGYLDIG_FORESPORSEL"),
    HTTP401_FEIL_AUTENTISERING("401_KLIENTEN_ER_IKKE_AUTENTISERT"),
    HTTP403_INGEN_TILGANG("403_KLIENTEN_ER_IKKE_AUTORISERT"),
    HTTP404_ANNEN_IKKE_FUNNET("404_ANNEN_IKKE_FUNNET"),
    HTTP404_FANT_IKKE_SAKSREF("404_SKE_FANT_IKKE_SAKSREF"),
    HTTP404_FANT_IKKE_SAKSREF_RESEND("404_SKE_FANT_IKKE_SAKSREF_RESEND"),
    HTTP406_FEIL_MEDIETYPE("406_FEIL_MEDIETYPE_I_REQUEST"),
    HTTP409_ANNEN_KONFLIKT("409_ANNEN_KONFLIKT"),
    HTTP409_IKKE_RESKONTROFORT_RESEND("409_KRAV_ER_IKKE_RESKONTROFØRT_RESEND"),
    HTTP409_IKKE_RESKONTROFORT("409_KRAV_ER_IKKE_RESKONTROFØRT"),
    HTTP409_KRAV_ER_AVSKREVET("409_KRAV_ER AVSKREVET"),
    HTTP422_ANNEN_VALIDERINGSFEIL("422_ANNEN VALIDERINGSFEIL"),
    HTTP422_VALIDERINGSFEIL("422_VALIDERINGSFEIL"),
    HTTP500_ANNEN_SERVER_FEIL("500_SERIE_ANNEN_SERVER_FEIL"),
    HTTP500_INTERN_TJENERFEIL("500_FEIL_PÅ_MOTTAKSERVER"),
    HTTP503_UTILGJENGELIG_TJENESTE("503_TJENESTEN_ER_IKKE_TILGJENGELIG"),
    ;

    companion object {
        private val map = Status.entries.associateBy { it.value }

        fun Status.isOkStatus(): Boolean {
            return when (this) {
                KRAV_IKKE_SENDT,
                KRAV_SENDT,
                MOTTATT_UNDERBEHANDLING,
                RESKONTROFOERT,
                HTTP409_IKKE_RESKONTROFORT_RESEND -> true
                else -> false
            }
        }

        fun Status.isResendStatus(): Boolean {
            return when (this) {
                KRAV_IKKE_SENDT,
                HTTP409_IKKE_RESKONTROFORT_RESEND,
                HTTP500_INTERN_TJENERFEIL,
                HTTP503_UTILGJENGELIG_TJENESTE -> true
                else -> false
            }
        }

        fun Status.isAlarm(): Boolean {
            return when (this) {
                HTTP400_UGYLDIG_FORESPORSEL,
                HTTP401_FEIL_AUTENTISERING,
                HTTP403_INGEN_TILGANG,
                HTTP404_FANT_IKKE_SAKSREF,
                HTTP404_ANNEN_IKKE_FUNNET,
                HTTP406_FEIL_MEDIETYPE,
                HTTP409_KRAV_ER_AVSKREVET,
                HTTP409_IKKE_RESKONTROFORT,
                HTTP409_ANNEN_KONFLIKT,
                HTTP422_VALIDERINGSFEIL,
                HTTP422_ANNEN_VALIDERINGSFEIL,
                UKJENT_FEIL,
                UKJENT_STATUS -> true
                else -> false
            }
        }
    }
}