package sokos.skd.poc.skdmodels.NyttOppdrag

import kotlinx.serialization.Serializable


@Serializable
data class YtelseForAvregningBeloep (
    val valuta: Valuta,
    val beloep: Long
)

@Serializable
data class TilleggsinformasjonNav (
    val stoenadstype: String,
    val ytelserForAvregning: YtelseForAvregningBeloep? = null
) {
    enum class Stoenadstype(val value: String){
        FORELDREPENGER("FORELDREPENGER"),
        KOMPENSASJONINNTEKSTAPFRILANSEROGNAERING("KOMPENSASJON_INNTEKSTAP_FRILANSER_OG_NAERING"),
        OMSORGOPPLAERINGOGPLEIEPENGER("OMSORG_OPPLAERING_OG_PLEIEPENGER"),
        AVTALEFESTETPENSJON("AVTALEFESTET_PENSJON"),
        AVTALEFESTETPENSJONPRIVATSEKTOR("AVTALEFESTET_PENSJON_PRIVATSEKTOR"),
        ALDERSPENSJON("ALDERSPENSJON"),
        BARNEPENSJON("BARNEPENSJON"),
        TIDLIGEREFAMILIEPLEIERPENSJON("TIDLIGERE_FAMILIEPLEIER_PENSJON"),
        GJENLEVENDEPENSJON("GJENLEVENDEPENSJON"),
        GAMMELYRKESSKADEPENSJON("GAMMEL_YRKESSKADEPENSJON"),
        KRIGSPENSJON("KRIGSPENSJON"),
        UFOEREPENSJON("UFOEREPENSJON"),
        REFUSSJONUTGIFTSDEKNING("REFUSSJON_UTGIFTSDEKNING"),
        SYKEPENGER("SYKEPENGER"),
        SVANGERSKAPSPENGER("SVANGERSKAPSPENGER"),
        UFOERETRYGD("UFOERETRYGD"),
        FORSKUDDTILBAKEKREVING("FORSKUDD_TILBAKEKREVING"),
        PERMITERINGSPENGERKORONA("PERMITERINGSPENGER_KORONA"),
        LOENSKOMPARBEIDSGIVERPERMITERTE("LOENSKOMP_ARBEIDSGIVER_PERMITERTE"),
        BARNETRYGD("BARNETRYGD"),
        OPPLAERINGSPENGER("OPPLAERINGSPENGER"),
        OMSORGSPENGER("OMSORGSPENGER"),
        PLEIEPENGERBARN("PLEIEPENGER_BARN"),
        PLEIEPENGERNAERSTAAENDE("PLEIEPENGER_NAERSTAAENDE"),
        ENSLIGFORSOERGEROVERGANGSSTOENAD("ENSLIG_FORSOERGER_OVERGANGSSTOENAD"),
        ENSLIGFORSOERGERBARNETILSYN("ENSLIG_FORSOERGER_BARNETILSYN"),
        ENSLIGFORSOERGERSKOLEPENGER("ENSLIG_FORSOERGER_SKOLEPENGER"),
        SUPPLERENDESTOENADUFOERE("SUPPLERENDE_STOENAD_UFOERE"),
        KONTANTSTOETTE("KONTANTSTOETTE");

        fun find(name: String) = values().firstOrNull(){it.name == name}
    }
}
