/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * Tjeneste for å opprette innkrevingsoppdrag
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *              Renter påløpt hos oppdragsgiver for overføring til innkrevingsmyndighet.         
 * @param valuta Kun norske kroner støttes per nå.
 * @param beloep Heltall, desimaler støttes ikke. Avrunding må i så fall gjøres hos oppdragsgiver. Angis som hovedenhet i valutaen, dvs. kroner ikke ører, euro ikke cent, osv. 
 * @param renterIlagtTidspunkt              Format: YYYY-MM-DD             Dato rentene ble ilagt, benyttes bl.a. til vurdering av dekningsrekkefølge.             
 */
data class RenteBeloep (

    /* Kun norske kroner støttes per nå. */
    val valuta: Valuta,
    /* Heltall, desimaler støttes ikke. Avrunding må i så fall gjøres hos oppdragsgiver. Angis som hovedenhet i valutaen, dvs. kroner ikke ører, euro ikke cent, osv.  */
    val beloep: kotlin.Long,
    /*              Format: YYYY-MM-DD             Dato rentene ble ilagt, benyttes bl.a. til vurdering av dekningsrekkefølge.              */
    val renterIlagtTidspunkt: java.time.LocalDate
) {
    /**
    * Kun norske kroner støttes per nå.
    * Values: NOK
    */
    enum class Valuta(val value: kotlin.String){
        NOK("NOK");
    }
}