/**
 * Tjenester for innkreving av krav for offentlige oppdragsgivere
 * Tjeneste for å opprette innkrevingsoppdrag
 *
 * OpenAPI spec version: local-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * Tilleggsinformasjon spesifikt for NAV
 * @param stoenadstype              Hvilken stønad/ytelse innkrevingsoppdraget gjelder. Brukes bl.a. i faktura og dialog med skyldner.          
 * @param referanseGammelSak              Referanse til gammel sak hos NAV.              Skal da matche \"oppdragsgiversSaksnummer\" fra et tidligere innkrevingsoppdrag.         
 * @param ytelserForAvregning 
 */
data class TilleggsinformasjonNav (

    /*              Hvilken stønad/ytelse innkrevingsoppdraget gjelder. Brukes bl.a. i faktura og dialog med skyldner.           */
    val stoenadstype: Stoenadstype,
    /*              Referanse til gammel sak hos NAV.              Skal da matche \"oppdragsgiversSaksnummer\" fra et tidligere innkrevingsoppdrag.          */
    val referanseGammelSak: kotlin.String? = null,
    val ytelserForAvregning: YtelseForAvregningBeloep? = null
) {
    /**
    *              Hvilken stønad/ytelse innkrevingsoppdraget gjelder. Brukes bl.a. i faktura og dialog med skyldner.          
    * Values: FORELDREPENGER,DAGPENGER
    */
    enum class Stoenadstype(val value: kotlin.String){
        FORELDREPENGER("FORELDREPENGER"),
        DAGPENGER("DAGPENGER");
    }
}